# Generated by Django 2.0.4 on 2018-04-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimage',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='image_url',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
